# Configuration settings for PySnake game
# Resolution settings
xlen = 40
ylen = 20
side = 60
# Game settings (Not work yet)
fps = 60
start_apples = 5
moving_per_second = 10
speed_per_apple = 0.5
change = -1
